#ifndef ONLINESHOPPINGSYSTEM_ONLINESHOPPINGSYSTEM_H
#define ONLINESHOPPINGSYSTEM_ONLINESHOPPINGSYSTEM_H


// Libraries
#include <stdlib.h>
#include <string.h>


#endif //ONLINESHOPPINGSYSTEM_ONLINESHOPPINGSYSTEM_H
